name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'

permissions:
  id-token: write
  contents: read

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_OIDC: true

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.0"

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        working-directory: infra
        run: terraform init

      - name: Find Public IP
        id: get_ip
        run: echo "ip=$(curl -s ifconfig.me)" >> "$GITHUB_OUTPUT"

      - name: Terraform Apply
        working-directory: infra
        run: |
          terraform apply -auto-approve \
            -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var="admin_ssh_public_key=${{ secrets.ARM_SSH_PUBLIC_KEY }}" \
            -var="allowed_ssh_ip=${{ steps.get_ip.outputs.ip }}" \
            -var="alert_email=${{ secrets.ALERT_EMAIL }}"